module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
    "./styles/**/*.css",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-fixed":               "var(--primary-container)",
        "on-surface-variant":          "var(--on-surface-variant)",
        "on-surface":                  "var(--on-surface)",
        "on-primary-fixed":            "var(--on-primary-fixed)",
        "tertiary-container":          "var(--tertiary-container)",
        "surface-bright":              "var(--surface-bright)",
        "error":                       "var(--error)",
        "surface-dim":                 "var(--surface)",
        "outline":                     "var(--outline)",
        "surface-container-low":       "var(--surface-container-low)",
        "secondary-dim":               "var(--secondary-dim)",
        "tertiary":                    "var(--tertiary)",
        "primary":                     "var(--primary)",
        "on-secondary":                "var(--on-secondary)",
        "error-dim":                   "var(--error-dim)",
        "on-background":               "var(--on-surface)",
        "on-secondary-container":      "var(--on-secondary-container)",
        "surface":                     "var(--surface)",
        "on-tertiary":                 "var(--on-tertiary)",
        "error-container":             "var(--error-container)",
        "secondary":                   "var(--secondary)",
        "surface-container-high":      "var(--surface-container-high)",
        "secondary-container":         "var(--secondary-container)",
        "on-primary":                  "var(--on-primary)",
        "on-primary-container":        "var(--on-primary-container)",
        "surface-tint":                "var(--primary)",
        "surface-container":           "var(--surface-container)",
        "surface-variant":             "var(--surface-container-highest)",
        "background":                  "var(--surface)",
        "outline-variant":             "var(--outline-variant)",
        "surface-container-highest":   "var(--surface-container-highest)",
        "primary-container":           "var(--primary-container)",
        "primary-dim":                 "var(--primary-dim)",
        "surface-container-lowest":    "var(--surface-container-lowest)",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg:      "0.25rem",
        xl:      "0.5rem",
        full:    "0.75rem",
      },
      fontFamily: {
        headline: ["Courier New", "ui-monospace", "monospace"],
        body:     ["Courier New", "ui-monospace", "monospace"],
        label:    ["Courier New", "ui-monospace", "monospace"],
      },
      keyframes: {
        "slide-up": {
          "0%":   { opacity: "0", transform: "translateY(16px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "fade-in": {
          "0%":   { opacity: "0" },
          "100%": { opacity: "1" },
        },
        "glow-pulse": {
          "0%, 100%": { boxShadow: "0 0 20px 2px rgba(143,245,255,0.08)" },
          "50%":      { boxShadow: "0 0 40px 8px rgba(143,245,255,0.22)" },
        },
      },
      animation: {
        "slide-up":   "slide-up 0.4s cubic-bezier(0.2,1,0.3,1) both",
        "fade-in":    "fade-in 0.3s ease both",
        "glow-pulse": "glow-pulse 2s ease-in-out infinite",
      },
    },
  },
  plugins: [],
};
