services:
  database:
    image: postgres:18-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    env_file: "./database/container/.env"
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./database/initdb.d:/docker-entrypoint-initdb.d
  backend:
    build:
      context: ./backend
      dockerfile: ./container/Dockerfile
      target: development
    restart: unless-stopped
    ports:
      - "3000:3000" # TODO dependent of an env file
    env_file: "./backend/container/.env"
    volumes:
      - ./backend/app:/app
      - backend_node_modules:/app/node_modules
      - ./database/initdb.d:/app/initdb.d/

  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
      target: development
    restart: unless-stopped
    ports:
      - "3001:3000"
    env_file: "./frontend/.env"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    environment:
    - NODE_ENV=development
    - WATCHPACK_POLLING=true
    depends_on:
      - backend
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certs:/etc/nginx/certs
    depends_on:
      - frontend
volumes:
  postgres_data:
  backend_node_modules:
  frontend_node_modules:
