import type { Metadata } from "next";

/**
 * Single source of truth for anything that ends up in a <head> tag, a
 * sitemap entry or a robots rule. Keeping it here means the canonical
 * host, the product name and the marketing copy can never drift apart
 * between the layout, the sitemap and the structured data.
 */

/**
 * Public origin the site is served from, with no trailing slash.
 *
 * Must be an absolute URL: `metadataBase`, canonicals, the sitemap and
 * JSON-LD all resolve against it, and relative values would silently
 * produce broken tags. Set NEXT_PUBLIC_SITE_URL at build time — it is
 * inlined into the client bundle, so changing it needs a rebuild.
 */
export const SITE_URL = (process.env.NEXT_PUBLIC_SITE_URL ?? "https://localhost")
  .replace(/\/+$/, "");

export const SITE_NAME = "Reversiverse";

/** Used for `title.template`, so keep it short — it is suffixed to every page title. */
export const SITE_TAGLINE = "Online Reversi Club";

export const SITE_DESCRIPTION =
  "Play Reversi (Othello) online against real opponents. Casual matchmaking, " +
  "private duels with friends, live chat, spectator mode and a global leaderboard.";

export const SITE_KEYWORDS = [
  "reversi",
  "othello",
  "play reversi online",
  "online reversi",
  "multiplayer reversi",
  "reversi board game",
  "othello online",
  "reversi matchmaking",
  "reversi leaderboard",
  "browser board game",
];

export const SITE_LOCALE = "en_US";

// Matches `--surface` in styles/globals.css
export const THEME_COLOR = "#211e1b";

// Matches `--primary` in styles/globals.css
export const BRAND_COLOR = "#d5a62b";

/** Absolute URL for `path`, which should start with a slash. */
export function absoluteUrl(path = "/"): string {
  return `${SITE_URL}${path.startsWith("/") ? path : `/${path}`}`;
}

export const OG_IMAGE_ALT = `${SITE_NAME} — play Reversi online against real opponents`;

/**
 * The social card, generated by app/opengraph-image.tsx. Referenced by an
 * explicit path rather than left to Next's file convention — see
 * `pageMetadata` for why that matters.
 */
export const OG_IMAGE = {
  url: "/opengraph-image",
  width: 1200,
  height: 630,
  alt: OG_IMAGE_ALT,
  type: "image/png",
} as const;

/**
 * Builds a complete Metadata object for one public route.
 *
 * Next.js does **not** deep-merge `openGraph` and `twitter`: a child route
 * that sets either one replaces the parent's version entirely, and that
 * also discards the image Next would otherwise attach from the
 * opengraph-image file convention. Overriding just a title in a child is
 * therefore enough to silently strip `og:image` and downgrade
 * `twitter:card` back to the small `summary` layout.
 *
 * Every public route goes through this helper so those fields are always
 * emitted in full.
 */
export function pageMetadata({
  title,
  description,
  path,
  socialTitle,
  socialDescription,
  robots,
}: {
  title: string;
  description: string;
  /** Route path, used for the canonical and `og:url`. */
  path: string;
  /** Shorter title for social cards; defaults to `title`. */
  socialTitle?: string;
  /** Shorter description for social cards; defaults to `description`. */
  socialDescription?: string;
  robots?: Metadata["robots"];
}): Metadata {
  const ogTitle = socialTitle ?? title;
  const ogDescription = socialDescription ?? description;

  return {
    title,
    description,
    alternates: { canonical: path },
    openGraph: {
      type: "website",
      siteName: SITE_NAME,
      locale: SITE_LOCALE,
      url: path,
      title: ogTitle,
      description: ogDescription,
      images: [OG_IMAGE],
    },
    twitter: {
      card: "summary_large_image",
      title: ogTitle,
      description: ogDescription,
      images: [OG_IMAGE],
    },
    ...(robots ? { robots } : {}),
  };
}

/**
 * Routes that are safe to crawl and index.
 *
 * Everything under the (logged) route group sits behind auth and renders
 * nothing useful to a crawler, so it is deliberately absent here and
 * blocked in robots.ts. `changeFrequency`/`priority` are hints only —
 * they are advisory for most crawlers, but cost nothing to state.
 */
export const PUBLIC_ROUTES = [
  { path: "/login", changeFrequency: "monthly", priority: 1.0 },
  { path: "/register", changeFrequency: "monthly", priority: 0.9 },
  { path: "/legal/terms", changeFrequency: "yearly", priority: 0.3 },
  { path: "/legal/privacy", changeFrequency: "yearly", priority: 0.3 },
] as const;

/**
 * Auth-gated or machine-only prefixes. Shared by robots.ts so the
 * disallow list cannot drift from what is actually private.
 */
export const PRIVATE_PATH_PREFIXES = [
  "/lobby",
  "/game",
  "/profile",
  "/friend",
  "/leaderboard",
  "/review",
  "/google",
  "/api",
  // In-app duplicates of the public legal pages; the /legal/* copies are canonical.
  "/terms",
  "/privacy",
];
